server:
  port: 8201
spring:
  profiles: dev
  application:
    name: config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka,http://localhost:9094/eureka
    register-with-eureka: false
  instance:
    instance-id: config-client
    prefer-ip-address: true

